### ISSUE TITLE
Exception raised

### ISSUE THREAD

**Issue by Z2Flow** [lorint/brick#9]
Ruby 3.2.2
Rails 7.0.8

I created a new Rails project and connected it to a simple database containing a single table (users).
When I executed this command:

`bin/rails g brick:models`

this was the result:

`
/Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/brick-1.0.175/lib/generators/brick/models_generator.rb:32:in `block in brick_models': undefined method `split' for :db_name:Symbol (NoMethodError)

        tbl_parts = tbl.split('.')
                       ^^^^^^
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/brick-1.0.175/lib/generators/brick/models_generator.rb:31:in `map'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/brick-1.0.175/lib/generators/brick/models_generator.rb:31:in `brick_models'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:134:in `block in invoke_all'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:134:in `each'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:134:in `map'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:134:in `invoke_all'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/group.rb:232:in `dispatch'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.8/lib/rails/generators.rb:263:in `invoke'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.8/lib/rails/commands/generate/generate_command.rb:26:in `perform'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.8/lib/rails/command/base.rb:87:in `perform'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.8/lib/rails/command.rb:48:in `invoke'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.8/lib/rails/commands.rb:18:in `<main>'
        from <internal:/Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from <internal:/Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from bin/rails:4:in `<main>'
`

**Comment by lorint** [comment]
Heya @Z2Flow -- thanks for the find!  These two were also affected in a similar way:
```
bin/rails g brick:migrations
bin/rails g brick:seeds
```
This had surfaced from the most recent latest release, so I've simply updated the commit regarding **connecting to database replicas** and then released a working version as [v1.0.176](https://github.com/lorint/brick/releases/tag/v1.0.176).

Thanks much!

**Comment by lorint** [comment]
Heya @Z2Flow -- thanks for the find!  These two were also affected in a similar way:
```
bin/rails g brick:migrations
bin/rails g brick:seeds
```
This had surfaced from the most recent latest release, so I've simply updated the commit regarding **connecting to database replicas** and then released a working version as [v1.0.176](https://github.com/lorint/brick/releases/tag/v1.0.176).

Thanks much!

**Comment by Z2Flow** [comment]
Thanks Lorin,

At first, I thought that I had somehow screwed up, being a noob to Rails.
Love The Brick!

Cheers,
Rob

**Comment by Z2Flow** [comment]
HI Lorint,

Just saw that I misspelled your name in my plast emai—apologies for that.

Cheers,
Rob

**Comment by lorint** [comment]
> misspelled your name

Not worried :)  Especially at the minute --
just got back this evening from a bangin' dance thing that my friend Anth put together.  Had the honour of being resident photographer, and have been hopping all around and loving life.

If you can think of cool things that would make The Brick more interesting, let me know!

-L

![PHOTO-2023-09-17-23-03-28](https://github.com/lorint/brick/assets/5301131/c6bc84b4-fd5d-41d4-92ea-ba3734eae525)

![PHOTO-2023-09-17-21-57-15](https://github.com/lorint/brick/assets/5301131/23802ba3-bfa2-49f9-be5a-aa1107164ef0)

**Comment by Z2Flow** [comment]
Looks like a blast.

I have a suggestion for The Brick - add the functionality of the gem schema_to_scaffold.

Cheers.

**Comment by Z2Flow** [comment]
Hey Lorint,

I have another one. I was playing around and getting an issue with generating migrations.
I then deleted all the models and then attempted to regenerate them and got this:

rails g brick:models    
/Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/brick-1.0.176/lib/brick/extensions.rb:1451:in `const_missing': uninitialized constant ApplicationRecord (NameError)

      self._brick_const_missing(*args) # ... rely solely on Zeitwerk.
          ^^^^^^^^^^^^^^^^^^^^^
Did you mean?  ApplicationJob
               ApplicationHelper
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/inflector/methods.rb:278:in `const_get'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/inflector/methods.rb:278:in `constantize'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/core_ext/string/inflections.rb:74:in `constantize'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/pay-6.8.1/app/models/pay/application_record.rb:2:in `<module:Pay>'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/pay-6.8.1/app/models/pay/application_record.rb:1:in `<main>'
        from <internal:/Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from <internal:/Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.11/lib/zeitwerk/kernel.rb:30:in `require'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/pay-6.8.1/app/models/pay/charge.rb:2:in `<module:Pay>'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/pay-6.8.1/app/models/pay/charge.rb:1:in `<main>'
        from <internal:/Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from <internal:/Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.11/lib/zeitwerk/kernel.rb:30:in `require'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/pay-6.8.1/lib/pay/engine.rb:39:in `block in <class:Engine>'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:445:in `instance_exec'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:445:in `block in make_lambda'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:199:in `block (2 levels) in halting'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:687:in `block (2 levels) in default_terminator'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:686:in `catch'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:686:in `block in default_terminator'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:200:in `block in halting'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:595:in `block in invoke_before'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:595:in `each'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:595:in `invoke_before'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/callbacks.rb:106:in `run_callbacks'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.0.8/lib/active_support/reloader.rb:88:in `prepare!'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.8/lib/rails/application/finisher.rb:68:in `block in <module:Finisher>'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.8/lib/rails/initializable.rb:32:in `instance_exec'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.8/lib/rails/initializable.rb:32:in `run'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.8/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `each'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `call'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.8/lib/rails/initializable.rb:60:in `run_initializers'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.8/lib/rails/application.rb:372:in `initialize!'
        from /Volumes/Lakshmi/Users/rob/RubymineProjects/H2Flow X3/config/environment.rb:5:in `<main>'
        from <internal:/Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from <internal:/Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/zeitwerk-2.6.11/lib/zeitwerk/kernel.rb:38:in `require'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.8/lib/rails/application.rb:348:in `require_environment!'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.8/lib/rails/command/actions.rb:28:in `require_environment!'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.8/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.8/lib/rails/commands/generate/generate_command.rb:21:in `perform'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.8/lib/rails/command/base.rb:87:in `perform'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.8/lib/rails/command.rb:48:in `invoke'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/railties-7.0.8/lib/rails/commands.rb:18:in `<main>'
        from <internal:/Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from <internal:/Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /Volumes/Lakshmi/Users/rob/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        from bin/rails:4:in `<main>'
